### ISSUE TITLE
(no response from author for month) incorrect currency exchange

### ISSUE THREAD

**Issue by ghost** [TehStoneMan/CashCraft#7]
don't worry anymore, i fixed it by myself  ;-)

**Comment by Das-Schnu** [comment]
I just looked at the content of the .jar and found the problem!
It's in data\cashcraft\recipes\break_note_hundred.json

### IT IS:
{
	"type": "minecraft:crafting_shapeless",
	"group": "cashcraft:note_100",
	"ingredients":
	[
		{ "item": "cashcraft:note_050" }
	],
	"result": { "item": "cashcraft:note_100", "count": 2 }
}

### IT SHOULD BE:
{
	"type": "minecraft:crafting_shapeless",
	"group": "cashcraft:note_100",
	"ingredients":
	[
		{ "item": "cashcraft:note_100" }
	],
	"result": { "item": "cashcraft:note_050", "count": 2 }
}
